project:
  type: website
  output-dir: docs

website:
  title: "WabiSabi"
  favicon: "images/logos/logov3"
  site-url: https://wabisabispaces.com
  description: "Soulful Spaces"
  open-graph:
    locale: en_US
  navbar:
    right:
      - text: "About Us"
        href: about.qmd
  page-footer:
    center: |
      <span class="container"><strong>[Contact us](mailto:contact@wabisabispaces.com){target="_blank"}</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/oshanmodi/wabisabispaces.com){target="_blank"}</strong></span>
    background: "#545551"
    
format:
  html:
    theme: 
      light: [sandstone, _variables.scss]
    css: styles.css

# format:
#   html:
#     theme: 
#       light: [sandstone, _variables.scss]
#       # light: [cosmo, _variables.scss]
#       # dark: [cosmo, theme_dark_custom.scss]
#     css: styles.css